include ../../config


CXXFLAGS += -Wno-sign-compare -Wno-conversion
INCLUDES += -I../utls

LIBS = curvlinear

curvlinear_CPPFILES = curvidetect1d.cpp curvidetect2d.cpp petrou.cpp curvlinear.cpp

$(do_libs)
