include ../../config


CXXFLAGS += -Wno-sign-compare -Wno-conversion
INCLUDES += -I../utls

LIBS = curvlinear

curvlinear_CPPFILES = CurviDetect1D.cpp CurviDetect2D.cpp Petrou.cpp curvlinear.cpp

$(do_libs)
